#!/usr/bin/env python3
"""Build deterministic coverage and curation reports for public PMM families."""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = ROOT / "data" / "families.yaml"
JSON_PATH = ROOT / "build" / "coverage-report.json"
MARKDOWN_PATH = ROOT / "docs" / "coverage-report.md"


def load_public_families() -> list[dict]:
    registry = yaml.safe_load(REGISTRY_PATH.read_text(encoding="utf-8"))
    families = []
    for entry in registry["datasets"]:
        if "family" not in entry:
            continue
        document = yaml.safe_load((ROOT / entry["source"]).read_text(encoding="utf-8"))
        families.append({**entry["family"], "source": entry["source"], "document": document})
    return families


def count(items: list[dict], field: str) -> dict[str, int]:
    return dict(sorted(Counter(item.get(field, "unspecified") for item in items).items()))


def review_reasons(claim: dict, evidence_by_id: dict[str, dict]) -> list[str]:
    reasons = []
    if claim["epistemic_status"] == "proposed":
        reasons.append("proposed claim")
    if claim["confidence"]["level"] in {"low", "very_low"}:
        reasons.append(f'{claim["confidence"]["level"]} confidence')
    evidence = [evidence_by_id[item] for item in claim.get("evidence_ids", [])]
    if evidence and all(item["domains"]["consistency"] == "single_source" for item in evidence):
        reasons.append("single-source support")
    if evidence and any(item["domains"]["precision"] == "limited" for item in evidence):
        reasons.append("limited precision")
    if claim["claim_type"] == "mediation" and claim.get("mediation_inference") == "statistical":
        reasons.append("statistical, not causal, mediation")
    return reasons


def build_report() -> dict:
    families = load_public_families()
    family_rows = []
    all_objects: list[dict] = []
    all_claims: list[dict] = []
    all_evidence: list[dict] = []
    all_sources: list[dict] = []
    review_queue = []

    for family in families:
        document = family["document"]
        objects = document["objects"]
        claims = document["claims"]
        evidence = document["evidence"]
        sources = document["sources"]
        evidence_by_id = {item["id"]: item for item in evidence}
        family_rows.append({
            "id": family["id"],
            "title": family["title"],
            "source": family["source"],
            "objects": len(objects),
            "claims": len(claims),
            "evidence": len(evidence),
            "sources": len(sources),
        })
        for claim in claims:
            reasons = review_reasons(claim, evidence_by_id)
            if reasons:
                review_queue.append({
                    "family_id": family["id"],
                    "claim_id": claim["id"],
                    "reasons": reasons,
                })
        all_objects.extend(objects)
        all_claims.extend(claims)
        all_evidence.extend(evidence)
        all_sources.extend(sources)

    return {
        "report_version": 1,
        "scope": "public_families",
        "family_count": len(families),
        "totals": {
            "objects": len(all_objects),
            "claims": len(all_claims),
            "evidence": len(all_evidence),
            "sources": len(all_sources),
        },
        "object_types": count(all_objects, "type"),
        "claim_types": count(all_claims, "claim_type"),
        "epistemic_statuses": count(all_claims, "epistemic_status"),
        "confidence_levels": count([item["confidence"] for item in all_claims], "level"),
        "evidence_kinds": count(all_evidence, "evidence_kind"),
        "support_directions": count(all_evidence, "support_direction"),
        "causal_support": count(all_evidence, "causal_support"),
        "families": family_rows,
        "review_queue": review_queue,
    }


def table(counter: dict[str, int]) -> str:
    return "\n".join(f"| `{key}` | {value} |" for key, value in counter.items())


def render_markdown(report: dict) -> str:
    totals = report["totals"]
    family_rows = "\n".join(
        f'| {item["title"]} | {item["objects"]} | {item["claims"]} | {item["evidence"]} | {item["sources"]} |'
        for item in report["families"]
    )
    queue = "\n".join(
        f'| `{item["family_id"]}` | `{item["claim_id"]}` | {", ".join(item["reasons"])} |'
        for item in report["review_queue"]
    ) or "| - | - | No rule-based flags |"
    return f"""# PMM coverage report

This file is generated by `scripts/build_coverage_report.py`. Counts describe the public mechanism families only; they measure curation coverage, not truth, importance, or prevalence in psychology.

## Snapshot

- Families: **{report['family_count']}**
- Objects: **{totals['objects']}**
- Claims: **{totals['claims']}**
- Evidence records: **{totals['evidence']}**
- Sources: **{totals['sources']}**
- Rule-based review flags: **{len(report['review_queue'])}**

## Families

| Family | Objects | Claims | Evidence | Sources |
|---|---:|---:|---:|---:|
{family_rows}

## Object types

| Type | Count |
|---|---:|
{table(report['object_types'])}

## Claim types

| Type | Count |
|---|---:|
{table(report['claim_types'])}

## Epistemic status

| Status | Count |
|---|---:|
{table(report['epistemic_statuses'])}

## Confidence

| Level | Count |
|---|---:|
{table(report['confidence_levels'])}

## Evidence profile

| Evidence kind | Count |
|---|---:|
{table(report['evidence_kinds'])}

### Support direction

| Direction | Count |
|---|---:|
{table(report['support_directions'])}

### Causal support

| Level | Count |
|---|---:|
{table(report['causal_support'])}

## Curation queue

Flags are deterministic prompts for review, not automatic scientific defects. A claim appears here when it is proposed, low-confidence, supported only by single-source evidence, limited in precision, or explicitly statistical rather than causal mediation.

| Family | Claim | Reasons |
|---|---|---|
{queue}
"""


def main() -> int:
    report = build_report()
    JSON_PATH.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    MARKDOWN_PATH.write_text(render_markdown(report), encoding="utf-8")
    print(f"built: {JSON_PATH.relative_to(ROOT)}")
    print(f"built: {MARKDOWN_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
